var sitemap = [
           	{
           		"match":"views",
           		"url":"/web/views/index.html",
           		"name":"首页",
           		"item":[
           		         {
           		        	"match":"news",
           	           		"url":"/web/views/news/list",
           	           		"name":"新闻",
                             "item":[
                                     {
                                         "match":"details",
                                         "url":"",
                                         "name":"{title}"//绑定字段，只限最后一级使用
                                     }]
           		         },
           		         {
        		        	"match":"about",
        	           		"url":"/ccs_web/modules/home/newslist.jsp",
        	           		"name":"关于我们",
                             "item":[
                                     {
                                         "match":"about1",
                                         "url":"",
                                         "name":"关于1"
                                     },{
                                         "match":"about2",
                                         "url":"",
                                         "name":"关于2"
                                     },{
                                         "match":"about3",
                                         "url":"",
                                         "name":"关于3"
                                     }]
            		     }
           		        ]
           	}
           ];
           	 